// Generated by src/build_data.py — edit that file, not this one.
const PACKAGES = [
 {
  "id": 6250889,
  "name": "Apartment Le Quartz 201",
  "kind": "Apartment",
  "aed": 10100,
  "basis": 4,
  "basisText": "Apartment based on four adults",
  "walkM": 600,
  "walkMin": 8,
  "revelDesc": "Located in Vieil Alpe, Quartz Residence offers ski-in/ski-out access opposite the lifts. This brand-new, south-facing 65sqm apartment features two bedrooms, a fully equipped kitchen, bright living spaces, balcony with mountain views, modern bathrooms and ski storage, ideal for a comfortable alpine stay.",
  "revelRoom": [
   "2 bedrooms - Type A (65m²)",
   "Self catering",
   "Kitchen",
   "1 Balcony",
   "1st bedroom: 2 sleeping places (1 x double bed) with ensuite bathroom",
   "2nd bedroom: 2 sleeping places (2 x Single bed)",
   "Bathroom 1: with shower",
   "Bathroom 2: with bathtub and toilet",
   "1 Separate toilet"
  ],
  "lat": 45.090488,
  "lng": 6.065626,
  "address": "308 Chemin de la Chapelle, Vieil Alpe",
  "extras": "Ski storage. No pool or spa mentioned.",
  "notes": [
   "One double bed and two single beds: three people can each have their own bed."
  ],
  "imgs": [
   "img/6250889_0.jpg",
   "img/6250889_1.jpg",
   "img/6250889_2.jpg",
   "img/6250889_3.jpg",
   "img/6250889_4.jpg",
   "img/6250889_5.jpg",
   "img/6250889_6.jpg",
   "img/6250889_7.jpg"
  ]
 },
 {
  "id": 6220637,
  "name": "Hotel Prestige Odalys L'Eclose - Apart'Hotel",
  "kind": "Apart'hotel room",
  "aed": 11350,
  "basis": 2,
  "basisText": "Room based on two adults",
  "walkM": 400,
  "walkMin": 5,
  "revelDesc": "Located beside the resort's chairlifts, L'Éclose offers well appointed apartments and hotel, a heated indoor pool, hammam, sauna and massage cabins. Enjoy convenient access to 250 km of slopes, with restaurants and shops nearby.",
  "revelRoom": [
   "Double room type A (Chambre Double - 23m²)"
  ],
  "lat": 45.088609,
  "lng": 6.071439,
  "address": "184 Rue du 93ème RAM, L'Éclose",
  "extras": "Heated indoor pool, hammam, sauna, massage cabins.",
  "notes": [
   "Priced per double room for two: three people need two rooms, so four places."
  ],
  "imgs": [
   "img/6220637_0.jpg",
   "img/6220637_1.jpg",
   "img/6220637_2.jpg",
   "img/6220637_3.jpg",
   "img/6220637_4.jpg",
   "img/6220637_5.jpg",
   "img/6220637_6.jpg",
   "img/6220637_7.jpg",
   "img/6220637_8.jpg"
  ]
 },
 {
  "id": 6221801,
  "name": "Apartment Le Hameau de Clotaire B23",
  "kind": "Apartment",
  "aed": 13500,
  "basis": 4,
  "basisText": "Apartment based on four adults",
  "walkM": 800,
  "walkMin": 12,
  "revelDesc": "Located in Alpe d'Huez's Cognet quarter, this 70sqm apartment with two double bedrooms, a sleeping alcove and two bathrooms. Enjoy mountain views, an east-facing balcony, fully equipped kitchen, indoor parking and ski locker, plus access to the residence's pool, sauna and hammam.",
  "revelRoom": [
   "2 bedrooms - Type A (70m²)",
   "Self catering",
   "Kitchen",
   "1 Balcony",
   "1st bedroom: 2 sleeping places (1 x double bed)",
   "2nd bedroom: 2 sleeping places (1 x double bed)",
   "Bathroom 1: bath, sink",
   "Bathroom 2: shower, sink, toilet",
   "Separate toilet: 1"
  ],
  "lat": 45.092082,
  "lng": 6.0644,
  "address": "99 Route du Coulet, Cognet",
  "extras": "Residence pool, sauna and hammam. Indoor parking, ski locker.",
  "notes": [
   "Both bedrooms have one double bed. Revel mentions a sleeping alcove but does not list its beds: ask what it sleeps."
  ],
  "imgs": [
   "img/6221801_0.jpg",
   "img/6221801_1.jpg",
   "img/6221801_2.jpg",
   "img/6221801_3.jpg",
   "img/6221801_4.jpg",
   "img/6221801_5.jpg",
   "img/6221801_6.jpg"
  ]
 },
 {
  "id": 6269852,
  "name": "Apartment Le Hameau de Clotaire B49",
  "kind": "Apartment",
  "aed": 14320,
  "basis": 4,
  "basisText": "Apartment based on four adults",
  "walkM": 800,
  "walkMin": 12,
  "revelDesc": "Located directly on the ski slopes, this modern apartment accommodates two bedrooms and two bathrooms. Enjoy a comfortable living area, balcony, fully equipped kitchen, and convenient access to shops and restaurants. Guests also benefit from an indoor pool, sauna, jacuzzi and gym.",
  "revelRoom": [
   "2 bedrooms - Type A (71m²)",
   "Self catering",
   "Kitchen",
   "1 Balcony",
   "1st bedroom: 2 sleeping places (1 x double bed)",
   "2nd bedroom: 2 sleeping places (1 x double bed)",
   "Bathroom 1: bath, sink",
   "Bathroom 2: shower, sink, toilet",
   "Separate toilet: 2"
  ],
  "lat": 45.092082,
  "lng": 6.0644,
  "address": "99 Route du Coulet, Cognet",
  "extras": "Indoor pool, sauna, jacuzzi and gym.",
  "notes": [
   "Revel lists two bedrooms, each with one double bed. The photos also show a twin-bed room and a bunk: ask Revel which rooms you get."
  ],
  "imgs": [
   "img/6269852_0.jpg",
   "img/6269852_1.jpg",
   "img/6269852_2.jpg",
   "img/6269852_3.jpg",
   "img/6269852_4.jpg",
   "img/6269852_5.jpg",
   "img/6269852_6.jpg",
   "img/6269852_7.jpg",
   "img/6269852_8.jpg",
   "img/6269852_9.jpg",
   "img/6269852_10.jpg",
   "img/6269852_11.jpg",
   "img/6269852_12.jpg"
  ]
 }
];
