#!/usr/bin/env python3
"""Builds data.js for the Revel packages page.
Revel facts are typed in from the brochure PDF (Tomorrowland-Winter-2027-AED.pdf, received 3 Oct 2026).
Photos are the full-size versions of the brochure's own shots, taken from Tomorrowland's listing of the same unit numbers (src/raw/img_<id>.json).
Coordinates come from the French national address API (api-adresse.data.gouv.fr), not the simulator."""
import json, re, glob, os
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
def clean(s): return re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', ' ', (s or '').replace('&nbsp;', ' ').replace('&amp;', '&'))).strip()

REVEL = [
 dict(id=6250889, name="Apartment Le Quartz 201", kind="Apartment", aed=10100, basis=4,
      basisText="Apartment based on four adults", walkM=600, walkMin=8,
      revelDesc="Located in Vieil Alpe, Quartz Residence offers ski-in/ski-out access opposite the lifts. This brand-new, south-facing 65sqm apartment features two bedrooms, a fully equipped kitchen, bright living spaces, balcony with mountain views, modern bathrooms and ski storage, ideal for a comfortable alpine stay.",
      revelRoom=["2 bedrooms - Type A (65m²)", "Self catering", "Kitchen", "1 Balcony", "1st bedroom: 2 sleeping places (1 x double bed) with ensuite bathroom", "2nd bedroom: 2 sleeping places (2 x Single bed)", "Bathroom 1: with shower", "Bathroom 2: with bathtub and toilet", "1 Separate toilet"],
      lat=45.090488, lng=6.065626, address="308 Chemin de la Chapelle, Vieil Alpe", extras="Ski storage. No pool or spa mentioned.", notes=["One double bed and two single beds: three people can each have their own bed."]),
 dict(id=6220637, name="Hotel Prestige Odalys L'Eclose - Apart'Hotel", kind="Apart'hotel room", aed=11350, basis=2,
      basisText="Room based on two adults", walkM=400, walkMin=5,
      revelDesc="Located beside the resort's chairlifts, L'Éclose offers well appointed apartments and hotel, a heated indoor pool, hammam, sauna and massage cabins. Enjoy convenient access to 250 km of slopes, with restaurants and shops nearby.",
      revelRoom=["Double room type A (Chambre Double - 23m²)"],
      lat=45.088609, lng=6.071439, address="184 Rue du 93ème RAM, L'Éclose",
      extras="Heated indoor pool, hammam, sauna, massage cabins.", notes=["Priced per double room for two: three people need two rooms, so four places."]),
 dict(id=6221801, name="Apartment Le Hameau de Clotaire B23", kind="Apartment", aed=13500, basis=4,
      basisText="Apartment based on four adults", walkM=800, walkMin=12,
      revelDesc="Located in Alpe d'Huez's Cognet quarter, this 70sqm apartment with two double bedrooms, a sleeping alcove and two bathrooms. Enjoy mountain views, an east-facing balcony, fully equipped kitchen, indoor parking and ski locker, plus access to the residence's pool, sauna and hammam.",
      revelRoom=["2 bedrooms - Type A (70m²)", "Self catering", "Kitchen", "1 Balcony", "1st bedroom: 2 sleeping places (1 x double bed)", "2nd bedroom: 2 sleeping places (1 x double bed)", "Bathroom 1: bath, sink", "Bathroom 2: shower, sink, toilet", "Separate toilet: 1"],
      lat=45.092082, lng=6.0644, address="99 Route du Coulet, Cognet",
      extras="Residence pool, sauna and hammam. Indoor parking, ski locker.", notes=["Both bedrooms have one double bed. Revel mentions a sleeping alcove but does not list its beds: ask what it sleeps."]),
 dict(id=6269852, name="Apartment Le Hameau de Clotaire B49", kind="Apartment", aed=14320, basis=4,
      basisText="Apartment based on four adults", walkM=800, walkMin=12,
      revelDesc="Located directly on the ski slopes, this modern apartment accommodates two bedrooms and two bathrooms. Enjoy a comfortable living area, balcony, fully equipped kitchen, and convenient access to shops and restaurants. Guests also benefit from an indoor pool, sauna, jacuzzi and gym.",
      revelRoom=["2 bedrooms - Type A (71m²)", "Self catering", "Kitchen", "1 Balcony", "1st bedroom: 2 sleeping places (1 x double bed)", "2nd bedroom: 2 sleeping places (1 x double bed)", "Bathroom 1: bath, sink", "Bathroom 2: shower, sink, toilet", "Separate toilet: 2"],
      lat=45.092082, lng=6.0644, address="99 Route du Coulet, Cognet",
      extras="Indoor pool, sauna, jacuzzi and gym.", notes=["Revel lists two bedrooms, each with one double bed. The photos also show a twin-bed room and a bunk: ask Revel which rooms you get."]),
]
out = []
for r in REVEL:
    n = len(json.load(open(f"{HERE}/raw/img_{r['id']}.json"))['Images'])
    r = dict(r); r.pop('roomMatch', None)
    r['imgs'] = [f"img/{r['id']}_{i}.jpg" for i in range(n)]   # same shots as the brochure's, at full size
    out.append(r)
open(f"{ROOT}/data.js", 'w').write("// Generated by src/build_data.py — edit that file, not this one.\nconst PACKAGES = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")
print('wrote data.js with', len(out), 'packages;', sum(len(o['imgs']) for o in out), 'photos')
